api_key: 
api_base: 
model:
temperature: 0
toolbench_url: http://8.130.32.149:8080/rapidapi
tools_folder: "./tools"
cache_folder: "./tool_response_cache"
is_save: true
port: 8082
log_file: "./server.log"