rm_url: http://11.216.49.126:8081/generate
# rm_url: http://11.220.92.38:8081/generate
# api_key: 8beCPow2KcmVGufSecmUZrTQhVN2OnPb
# api_base: https://gptproxy.llmpaas.woa.com/v1
# model: gpt-35-turbo-16k-0613-nlp

api_key: limyoona
api_base: http://11.216.49.126:8080/v1
# api_base: http://11.213.113.102:8081/v1
model: Qwen2.5-7B-Instruct
# model: Qwen2-7B-Instruct
max_tokens: 2048

temperature: 0.9
top_p: 0.95
n: 2

tmdb_headers: {"Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwZGJhYjU5MGM3ZWFjYTA3ZWJlNjI1OTc0YTM3YWQ5MiIsInN1YiI6IjY1MmNmODM3NjYxMWI0MDBmZmM3MDM5OCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.McsK4Wm5XnRSDLn62Jhy787YUAwZcQz0X5qzkGuLe_s"}
