# api_key: 8beCPow2KcmVGufSecmUZrTQhVN2OnPb
# api_base: https://gptproxy.llmpaas.woa.com/v1
# model: gpt-4o
api_key: 1813041960262017054
api_base: https://aigc.sankuai.com/v1/openai/native
model: gpt-4o-mini #"gpt-4-0125-preview"#'GPT-3.5-Turbo-1106'#"gpt-4-1106-preview" #'deepseek-chat' #'gpt-4o-2024-05-13'
temperature: 0.9
top_p: 0.95
n: 2
toolbench_key: qW5Tegl6dHMocJuaLPvYRnsOIyw0Dzi3mBjhU9G87ArKCtxZ2Q
stabletoolbench_server: http://0.0.0.0:8082/virtual
MAX_DEPTH: 5




